namespace ApiService.MetadataMicroservice.JsonMoedls
{
    public enum BatteryComponentParameterEnum
    {
        BatteryLifespan = 1,
        BatteryDod = 2,
        BatteryCRate = 3,
        BatteryEfficiency = 4,
        BatteryСellPrice = 6,
        BatteryСellCapacity = 15,
        BatteryEnergy = 18,
        YearlyBatteryPrice = 22,
        Cycle = 23,
        CapacityCost = 32,
        FcrRevenue = 33,
        BatteryCellType = 161,
        BatteryCellCount = 162,
        BatteryCapacity = 163,
        InverterType = 164,
        BatteryPrice = 165,
        BatteryRelativePrice = 166,
        BatteryDegradation = 214,
        BatteryMaxCycles = 215,
        BatteryPower = 216,
        OperationalCost = 217,
        MaxInjection = 219,
        BatteryDegradationPerMonth = 1223,
        InverterEfficiency = 1224,
        BatteryBEfficiency = 1225,
        BatteryVoltage = 1226,
        BatteryEolCapacity = 1227,
        Power = 1304,
        CRate = 1305,
        Dod = 1306,
        CapacityTotal = 1307,
        CapacityDegradationPerMonth = 1308,
        CapacityMaxCycles = 1309,
        Lifespan = 1310,
        ChargeMaxPower = 1311,
        ChargeEfficiency = 1312,
        ChargeMaxState = 1313,
        DischargeMaxPower = 1314,
        DischargeEfficiency = 1315,
        BatterySelfDischarge = 1316,
        FsrReverse = 1317,
        OperationsDcActivePower = 1318,
        OperationsDcActiveEnergy = 1319,
        Temperature = 1320,
        Guid = 1321,
        Model = 1372,
        OldId = 1413
    }
}